config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users
  resources :lab_reports

  root 'users#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lab_report.rb
# frozen_string_literal: true

class LabReport < ApplicationRecord
  belongs_to :user

  GRADES = %w[A B C D E FX F].freeze

  validates :title, presence: true, length: { maximum: 250 }
  validates :description, presence: true, length: { maximum: 500 }
  validates :grade, inclusion: { in: GRADES }

  def self.user_options
    User.all.collect { |u| [u.first_name, u.id] }
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :lab_reports, dependent: :destroy

  validates :first_name, presence: true, length: { maximum: 100 }
  validates :last_name, presence: true, length: { maximum: 100 }
  validates :email, presence: true, length: { maximum: 150 }, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/lab_reports_controller.rb
# frozen_string_literal: true

class LabReportsController < ApplicationController
  before_action :set_lab_report, only: %i[show edit update destroy]

  def index
    @lab_reports = LabReport.order(id: :asc)
  end

  def show; end

  def new
    @lab_report = LabReport.new
  end

  def create
    @lab_report = LabReport.new(lab_report_params)
    if @lab_report.save
      redirect_to lab_reports_path, notice: 'Отчет о лабораторной работе успешно создан'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @lab_report.update(lab_report_params)
      redirect_to lab_report_path(@lab_report)
    else
      render :edit
    end
  end

  def destroy
    @lab_report.destroy
    redirect_to lab_reports_path
  end

  private

  def set_lab_report
    @lab_report = LabReport.find(params[:id])
  end

  def lab_report_params
    params.require(:lab_report).permit(:title, :description, :user_id, :grade)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.order(id: :asc)
  end

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'Пользователь успешно создан.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/lab_reports/_form.html.erb
<%= form_with(model: [ @user, @lab_report ], local: true) do |form| %>
  <% if @lab_report.errors.any? %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold">Упс!</strong>
      <span class="block sm:inline">
        <%= pluralize(@lab_report.errors.count, "ошибка") %> запрещают сохранение:
      </span>
      <ul>
        <% @lab_report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :title, 'Заголовок', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :description, 'Описание', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_area :description, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :user, 'Студент', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.select :user_id, LabReport.user_options, {}, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :grade, 'Оценка', class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.select :grade, LabReport::GRADES, {}, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.submit 'Сохранить', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/lab_reports/edit.html.erb
<div class="max-w-md mx-auto px-4 sm:px-6 lg:px-8">
  <h1 class="text-3xl font-bold mb-4">Редактировать отчет о лабораторной работе</h1>

  <%= render 'form', lab_report: @lab_report %>

  <%= link_to 'Назад', lab_reports_path, class: "mt-4 inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-gray-600 hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500" %>
</div>

app/views/lab_reports/index.html.erb
<h1 class="text-3xl font-bold mb-4">Список отчетов о лабораторных работах</h1>

<%= link_to 'Добавить отчет', new_lab_report_path, class: "py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
<div class="my-6">
  <table class="table-auto w-full">
    <thead>
    <tr>
      <th class="py-2 px-4 bg-gray-100 border-b border-gray-200">№</th>
      <th class="py-2 px-4 bg-gray-100 border-b border-gray-200">Заголовок</th>
      <th class="py-2 px-4 bg-gray-100 border-b border-gray-200">Описание</th>
      <th class="py-2 px-4 bg-gray-100 border-b border-gray-200">Студент</th>
      <th class="py-2 px-4 bg-gray-100 border-b border-gray-200">Оценка</th>
      <th class="py-2 px-4 bg-gray-100 border-b border-gray-200"></th>
      <th class="py-2 px-4 bg-gray-100 border-b border-gray-200"></th>
    </tr>
    </thead>
    <tbody>
    <% @lab_reports.each do |lab_report| %>
      <tr>
        <td class="border px-4 py-2"><%= link_to lab_report.id, lab_report %></td>
        <td class="border px-4 py-2"><%= lab_report.title %></td>
        <td class="border px-4 py-2"><%= lab_report.description %></td>
        <td class="border px-4 py-2"><%= lab_report.user.first_name %></td>
        <td class="border px-4 py-2"><%= lab_report.grade %></td>
        <td class="border px-4 py-2">
          <%= link_to 'Редактировать', edit_lab_report_path(lab_report), class: "text-indigo-600 hover:text-indigo-900" %></td>
        <td class="border px-4 py-2">
          <%= button_to 'Удалить', lab_report_path(lab_report), method: :delete, data: { turbo_confirm: 'Вы уверены?' }, class: "text-red-600 hover:text-red-900" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/lab_reports/new.html.erb
<div class="max-w-md mx-auto px-4 sm:px-6 lg:px-8">
  <h1 class="text-3xl font-bold mb-4">Создать отчет о лабораторной работе</h1>

  <%= render 'form', lab_report: @lab_report %>
  <%= link_to 'Назад', lab_reports_path, class: "mt-4 inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-gray-600 hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500" %>
</div>

app/views/lab_reports/show.html.erb
<div class="p-6 bg-white border-b border-gray-200">
  <h1 class="text-3xl font-bold mb-4">Отчет о лабораторной работе</h1>

  <div class="mb-4">
    <h3 class="text-xl font-bold"><%= @lab_report.title %></h3>
    <p class="text-gray-700 mb-2"><%= @lab_report.description %></p>
    <p class="text-gray-700"><strong>Оценка:</strong> <%= @lab_report.grade %></p>
  </div>

  <div class="flex justify-between">
    <%= link_to 'Редактировать', edit_lab_report_path(@lab_report), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    <%= link_to 'Вернуться к списку', lab_reports_path, class: "bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->
<div class="bg-gray-800 w-64 space-y-6 py-7 px-2 absolute inset-y-0 left-0 transform -translate-x-full md:relative md:translate-x-0 transition duration-200 ease-in-out">
  <nav>
    <a href="<%= root_path %>" class="block py-2.5 px-4 text-sm text-white hover:bg-gray-700 rounded">
      Главная
    </a>
    <a href="<%= lab_reports_path %>" class="block py-2.5 px-4 text-sm text-white hover:bg-gray-700 rounded">
      Отчеты
    </a>
    <a href="<%= users_path %>" class="block py-2.5 px-4 text-sm text-white hover:bg-gray-700 rounded">
      Студенты
    </a>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LabRepots</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100 font-sans leading-normal tracking-normal">
    <div id="app" class="flex h-screen">
      <%= render 'layouts/sidebar' %>

      <main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-100">
        <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
          <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
            <div class="p-6 bg-white border-b border-gray-200">
              <%= yield %>
            </div>
          </div>
        </div>
      </main>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, class: "w-full max-w-md mx-auto") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 mb-4 rounded relative" role="alert">
      <h2 class="font-bold">Ошибка: <%= pluralize(user.errors.count, "error") %> запрещают сохранение пользователя:</h2>

      <ul class="list-disc list-inside">
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :first_name, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :first_name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :last_name, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :last_name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :email, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <%= form.text_field :email, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.submit 'Сохранить', class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="max-w-md mx-auto px-4 sm:px-6 lg:px-8">
  <h1 class="text-3xl font-bold mb-4">Редактирование студента</h1>

  <%= render 'form', user: @user %>
  <%= link_to 'Отмена', users_path, class: "mt-4 inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-gray-600 hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500" %>
</div>

app/views/users/index.html.erb
<h1 class="text-2xl font-bold mb-4">Список студентов</h1>

<%= link_to 'Добавить студента', new_user_path, class: "py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
<div class="my-6">
  <table class="table-auto w-full">
    <thead>
    <tr>
      <th class="py-2 px-4 bg-gray-100 border-b border-gray-200">№</th>
      <th class="py-2 px-4 bg-gray-100 border-b border-gray-200">Имя</th>
      <th class="py-2 px-4 bg-gray-100 border-b border-gray-200">Фамилия</th>
      <th class="py-2 px-4 bg-gray-100 border-b border-gray-200">Email</th>
      <th class="py-2 px-4 bg-gray-100 border-b border-gray-200">Действия</th>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="border px-4 py-2"><%= link_to user.id, user %></td>
        <td class="border px-4 py-2 break-words"><%= user.first_name %></td>
        <td class="border px-4 py-2"><%= user.last_name %></td>
        <td class="border px-4 py-2"><%= user.email %></td>
        <td class="border px-4 py-2">
          <%= link_to 'Редактировать', edit_user_path(user), class: "text-indigo-600 hover:text-indigo-900" %>
          <%= button_to 'Удалить', user_path(user), method: :delete, data: { turbo_confirm: 'Вы уверены?' }, class: "text-red-600 hover:text-red-900" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<div class="max-w-md mx-auto px-4 sm:px-6 lg:px-8">
  <h1 class="text-3xl font-bold mb-4">Создание нового студента</h1>

  <%= render 'form', user: @user %>
  <%= link_to 'Отмена', users_path, class: "mt-4 inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-gray-600 hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500" %>
</div>

app/views/users/show.html.erb
<div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
  <h1 class="text-3xl font-bold mb-4">Информация о пользователе</h1>

  <div class="bg-white shadow overflow-hidden sm:rounded-lg mb-8">
    <div class="px-4 py-5 sm:px-6">
      <dl class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2">
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">Имя</dt>
          <dd class="mt-1 text-lg text-gray-900"><%= @user.first_name %></dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">Фамилия</dt>
          <dd class="mt-1 text-lg text-gray-900"><%= @user.last_name %></dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">Email</dt>
          <dd class="mt-1 text-lg text-gray-900"><%= @user.email %></dd>
        </div>
      </dl>
    </div>
  </div>

  <div class="flex items-center justify-between">
    <%= link_to 'Редактировать', edit_user_path(@user), class: "py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
    <%= link_to 'Вернуться к списку', users_path, class: "py-2 px-4 border border-transparent text-sm font-medium rounded-md text-indigo-600 bg-white hover:bg-indigo-50" %>
  </div>
</div>